### PR TITLE
AbsoluteManageExport

### PR DESCRIPTION
**Pull request by tburgin**
Here is a processor that takes as input a pkg or executable and a SDPackages.ampkgprops (plist config) to output a .amsdpackages for use in Absolute Manage. If no SDPackages.ampkgprops is specified a default config will be generated.

You can use this processor by making a new recipe or by adding an override like shown below.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Identifier</key>
	<string>local.pkg.AdobeFlashPlayer</string>
	<key>Input</key>
	<dict>
		<key>NAME</key>
		<string>AdobeFlashPlayer</string>
	</dict>
	<key>ParentRecipe</key>
	<string>com.github.autopkg.pkg.FlashPlayerExtractPackage</string>
	<key>Process</key>
	<array>
		<dict>
			<key>Comment</key>
			<string>Export the embedded package into .amsdpackages to use in Absolute Manage</string>
			<key>Arguments</key>
			<dict>
				<key>source_payload_path</key>
				<string>%RECIPE_CACHE_DIR%/%NAME%-%version%.pkg</string>
				<key>dest_payload_path</key>
				<string>%RECIPE_CACHE_DIR%/%NAME%-%version%.amsdpackages</string>
				<key>sdpackages_ampkgprops_path</key>
				<string>/Users/burgintj/Desktop/SDPackages.ampkgprops</string
				<key>import_abman_to_servercenter</key>
				</true>
			</dict>
			<key>Processor</key>
			<string>AbsoluteManageExport</string>
		</dict>
	</array>
</dict>
</plist>
```

### CODE REVIEW

**Comment by tburgin** [comment]
Just getting back into this...

**Comment by tburgin** [comment]
I have submitted a fresh case with Absolute Manage.

**Comment by tburgin** [comment]
I received word from one of the engineers that most likely our feature request will not happen this quarter. 

Like we have discussed in the past...
If you always run autopkg from the same system, duplicate packages will not be imported into Absolute Manage. This "works" but I don't like it. I would much rather have Absolute Manage be the driving factor and be able to run atopkg from any system without duplicate consequences.

He did send me this:
http://forums.absolute.com/kb.php?a=1062

```xml
<key>Processor</key>
<string>StopProcessingIf</string> -- Stop processing if no updated version was found.
<key>Arguments</key>
<dict>
<key>predicate</key>
<string>new_package_request == FALSE</string>
```
Assuming I am always running it from the same machine, packages will not get re-downloaded or duplicated into AM.

```bash
#!/bin/sh -x


# Update all repos
repos=`autopkg repo-list | awk '//{print $1}'`
for i in $repos;do
    autopkg repo-update $i ;
done

# Execute all recipes for Absolute
recipes=`autopkg list-recipes | grep -i absolute`
for i in $recipes;do
    autopkg run $i ;
done
```

**Comment by arubdesu** [comment]
uh, any particular reason this script seems to be replicating the functionality of ```repo-update all``` and ```run --list /path/to/listOfAMrecipes.txt```?

**Comment by tburgin** [comment]
No reason, Just pasted what I got from the Absolute Manage engineer. Guess he didn't know about that feature

**Comment by tburgin** [comment]
I dig some digging and found that Absolute Manage actually keeps a cached version of the Software Distribution Packages database (sqlite3). I have updated the AbsoluteManageExport to do some basic checking to prevent duplicates.

https://github.com/tburgin/AbsoluteManageExport

The processor runs fine when installed locally. However I am having trouble using it as a shared processor.

I add this repo

```
https://github.com/tburgin/AbsoluteManageExport
```

And use this recipe.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Description</key>
    <string>Creates an Absolute Manage package (.amsdpackages), imports it into the Absolute Manage Admin console and uploads it to the Absolute Manage Server.</string>
    <key>Identifier</key>
	<string>com.github.tburgin.tburgin-recipes.Absolute.AdobeFlashPlayer</string>
	<key>Input</key>
	<dict>
		<key>NAME</key>
		<string>AdobeFlashPlayer</string>
	</dict>
	<key>ParentRecipe</key>
	<string>com.github.autopkg.pkg.FlashPlayerExtractPackage</string>
	<key>MinimumVersion</key>
    <string>0.4.0</string>
	<key>Process</key>
	<array>
		<dict>
			<key>Processor</key>
			<string>com.github.tburgin.AbsoluteManageExport/AbsoluteManageExport</string>
			<key>Arguments</key>
			<dict>
				<key>dest_payload_path</key>
				<string>%RECIPE_CACHE_DIR%/%NAME%-%version%.amsdpackages</string>
				<key>sdpackages_ampkgprops_path</key>
				<string>%RECIPE_DIR%/%NAME%-Defaults.ampkgprops</string>
				<key>source_payload_path</key>
				<string>%pkg_path%</string>
                <key>import_abman_to_servercenter</key>
                <true/>
			</dict>
			<key>SharedProcessorRepoURL</key>
            <string>https://github.com/tburgin/AbsoluteManageExport</string>
		</dict>
	</array>
</dict>
</plist>
```

But Always get this:

```
Processing AdobeFlashPlayer.Absolute...
Failed.
Receipt written to /tmp/receipts/AdobeFlashPlayer-receipt-20150224-102723.plist

The following recipes failed:
    AdobeFlashPlayer.Absolute
        Unknown processor 'com.github.tburgin.AbsoluteManageExport/AbsoluteManageExport'. This shared processor can be added via the repo: https://github.com/tburgin/AbsoluteManageExport.

Nothing downloaded, packaged or imported.
```

**Comment by yngast** [comment]
I noticed that Adobe renamed the dmg, one have to add Install at the end of the name in the download recipe for it to download.
Don’t know if that helps
Yngve

**Comment by timsutton** [comment]
When you refer to a shared processor like: `com.github.tburgin.AbsoluteManageExport/AbsoluteManageExport`, the part preceding the slash is a recipe identifier. So I'd think it should work if you change this to `com.github.tburgin.AbsoluteManageExport.AdobeFlashPlayer`, or alternatively make a stub recipe called `com.github.tburgin.AbsoluteManageExport` as suggested in the Processor Locations wiki page.

**Comment by tburgin** [comment]
@timsutton Thanks. I uploaded a stub recipe to the repo. Using AbsoluteManageExport as a shared processor now works well.

**Comment by tburgin** [comment]
AbsoluteManageExport is being hosted here. Closing this issue.
https://github.com/tburgin/AbsoluteManageExport

**Pull request closed without merging**
