### PR TITLE
Add support for internal GitHub urls

### PR DESCRIPTION
**Pull request by bfreezy**
###Summary
Add support for AutoPkg users to override the default GitHub API URL and API token location when using the GitHubReleasesInfoProvider. This would allow organizations to search against an internal GitHub Enterprise instance. Additionally, if they choose to search against an internal instance, one can specify a specific token location path on the disk (can be either a relative path or absolute path).

###How?

**Additions to GitHubSession**
I changed the GitHubSession constructor and added two new parameters: `github_url` and `token_path` and a new class attribute: `self.url`.

If the `github_url` parameter is set, then it assigns `self.url` to its value, otherwise, it will use the constant `BASE_URL` (https://api.github.com) as its value.

The `token_path` defaults to the constant `TOKEN_LOCATION` (~/.autopkg_gh_token).

**Additions to GitHubReleasesInfoProvider**
- `GITHUB_URL`:  This new input is passed as the `github_url` parameter
- `GITHUB_TOKEN_PATH`: This new input is passed as the `token_path` parameter

###Testing

**autopkg search**
```
$:~/autopkg/Code|bfreezy/add-support-for-internal-github-urls⚡
⇒  ./autopkg search GoogleChrome

Name                                    Repo                      Path
----                                    ----                      ----
GoogleChrome-Win64.filewave.recipe      andredb90-recipes         Google/GoogleChrome-Win64.filewave.recipe
ChromeRemoteDesktop.munki.recipe        apizz-recipes             Chrome_Remote_Desktop/ChromeRemoteDesktop.munki.recipe
GoogleChrome.filewave.recipe            filewave                  GoogleChrome/GoogleChrome.filewave.recipe
GoogleChromeCanary.download.recipe      foigus-recipes            Google/GoogleChromeCanary.download.recipe
GoogleChromeEnterprise.munki.recipe     grahamgilbert-recipes     Google/GoogleChromeEnterprise.munki.recipe
GoogleChrome-Win.download.recipe        hansen-m-recipes          Google/GoogleChrome-Win.download.recipe
GoogleChrome-Win64.download.recipe      hansen-m-recipes          Google/GoogleChrome-Win64.download.recipe
Google Chrome.jss.recipe                jss-recipes               Google Chrome/Google Chrome.jss.recipe
Google Chrome.jss.recipe                novaksam-recipes          Google Chrome/Google Chrome.jss.recipe
GoogleChrome-Win32.LANrev.recipe        patgmac-recipes           Google Chrome/GoogleChrome-Win32.LANrev.recipe
GoogleChrome-Win64.LANrev.recipe        patgmac-recipes           Google Chrome/GoogleChrome-Win64.LANrev.recipe
GoogleChrome.pkg.recipe                 recipes                   GoogleChrome/GoogleChrome.pkg.recipe
GoogleChrome.download.recipe            recipes                   GoogleChrome/GoogleChrome.download.recipe
GoogleChromePkg.download.recipe         recipes                   GoogleChrome/GoogleChromePkg.download.recipe
GoogleChrome.install.recipe             recipes                   GoogleChrome/GoogleChrome.install.recipe
GoogleChrome.munki.recipe               recipes                   GoogleChrome/GoogleChrome.munki.recipe
GoogleChromePkg.pkg.recipe              recipes                   GoogleChrome/GoogleChromePkg.pkg.recipe
GoogleChromePkg.munki.recipe            recipes                   GoogleChrome/GoogleChromePkg.munki.recipe
GoogleChrome.jss.recipe                 rtrouton-recipes          JSS/GoogleChrome.jss.recipe
GoogleChrome.install.recipe             rtrouton-recipes          GoogleChrome/GoogleChrome.install.recipe
GoogleChrome.pkg.recipe                 rtrouton-recipes          GoogleChrome/GoogleChrome.pkg.recipe
GoogleChromeEnterprise.jss.recipe       rtrouton-recipes          JSS/GoogleChromeEnterprise.jss.recipe
GoogleChromeUSC.jss.recipe              scriptingosx-recipes      GoogleChrome/GoogleChromeUSC.jss.recipe
GoogleChromeUSC.pkg.recipe              scriptingosx-recipes      GoogleChrome/GoogleChromeUSC.pkg.recipe
GoogleChrome.LANrev.recipe              seansgm-recipes           LANrevRecipes/GoogleChrome.LANrev.recipe
GoogleChrome.Absolute.recipe            seansgm-recipes           AbsoluteRecipes/GoogleChrome.Absolute.recipe
GoogleChrome.ds.recipe                  triti-recipes             GoogleChrome/GoogleChrome.ds.recipe

To add a new recipe repo, use 'autopkg repo-add <repo name>'
```

Using the `-t` flag with autopkg search:
```
$:~/autopkg/Code|bfreezy/add-support-for-internal-github-urls⚡
⇒  ./autopkg search GoogleChrome -t
Create a new token in your GitHub settings page:

    https://github.com/settings/tokens

To save the token, paste it to the following prompt.
Token: <redacted>
Writing token file /Users/brandonfriess/.autopkg_gh_token.

Name                                    Repo                      Path
----                                    ----                      ----
GoogleChrome-Win64.filewave.recipe      andredb90-recipes         Google/GoogleChrome-Win64.filewave.recipe
ChromeRemoteDesktop.munki.recipe        apizz-recipes             Chrome_Remote_Desktop/ChromeRemoteDesktop.munki.recipe
GoogleChrome.filewave.recipe            filewave                  GoogleChrome/GoogleChrome.filewave.recipe
GoogleChromeCanary.download.recipe      foigus-recipes            Google/GoogleChromeCanary.download.recipe
GoogleChromeEnterprise.munki.recipe     grahamgilbert-recipes     Google/GoogleChromeEnterprise.munki.recipe
GoogleChrome-Win.download.recipe        hansen-m-recipes          Google/GoogleChrome-Win.download.recipe
GoogleChrome-Win64.download.recipe      hansen-m-recipes          Google/GoogleChrome-Win64.download.recipe
Google Chrome.jss.recipe                jss-recipes               Google Chrome/Google Chrome.jss.recipe
Google Chrome.jss.recipe                novaksam-recipes          Google Chrome/Google Chrome.jss.recipe
GoogleChrome-Win32.LANrev.recipe        patgmac-recipes           Google Chrome/GoogleChrome-Win32.LANrev.recipe
GoogleChrome-Win64.LANrev.recipe        patgmac-recipes           Google Chrome/GoogleChrome-Win64.LANrev.recipe
GoogleChrome.pkg.recipe                 recipes                   GoogleChrome/GoogleChrome.pkg.recipe
GoogleChrome.download.recipe            recipes                   GoogleChrome/GoogleChrome.download.recipe
GoogleChromePkg.download.recipe         recipes                   GoogleChrome/GoogleChromePkg.download.recipe
GoogleChrome.install.recipe             recipes                   GoogleChrome/GoogleChrome.install.recipe
GoogleChrome.munki.recipe               recipes                   GoogleChrome/GoogleChrome.munki.recipe
GoogleChromePkg.pkg.recipe              recipes                   GoogleChrome/GoogleChromePkg.pkg.recipe
GoogleChromePkg.munki.recipe            recipes                   GoogleChrome/GoogleChromePkg.munki.recipe
GoogleChrome.jss.recipe                 rtrouton-recipes          JSS/GoogleChrome.jss.recipe
GoogleChrome.install.recipe             rtrouton-recipes          GoogleChrome/GoogleChrome.install.recipe
GoogleChrome.pkg.recipe                 rtrouton-recipes          GoogleChrome/GoogleChrome.pkg.recipe
GoogleChromeEnterprise.jss.recipe       rtrouton-recipes          JSS/GoogleChromeEnterprise.jss.recipe
GoogleChromeUSC.jss.recipe              scriptingosx-recipes      GoogleChrome/GoogleChromeUSC.jss.recipe
GoogleChromeUSC.pkg.recipe              scriptingosx-recipes      GoogleChrome/GoogleChromeUSC.pkg.recipe
GoogleChrome.LANrev.recipe              seansgm-recipes           LANrevRecipes/GoogleChrome.LANrev.recipe
GoogleChrome.Absolute.recipe            seansgm-recipes           AbsoluteRecipes/GoogleChrome.Absolute.recipe
GoogleChrome.ds.recipe                  triti-recipes             GoogleChrome/GoogleChrome.ds.recipe

To add a new recipe repo, use 'autopkg repo-add <repo name>'
```

**AutoPkg run with public GitHub**
```
$: ./autopkg run --ignore-parent-trust-verification-errors /Users/brandonfriess/autopkg/Flycut/Flycut.download.recipe -vvvv
Processing /Users/brandonfriess/autopkg/Flycut/Flycut.download.recipe...
{'AUTOPKG_VERSION': '2.1.1',
 'FAIL_RECIPES_WITHOUT_TRUST_INFO': True,
 'GITHUB_REPO': 'TermiT/Flycut',
 'MUNKI_REPO': '/Users/brandonfriess/munki-mac-packages/public',
 'NAME': 'flycut',
 'PARENT_RECIPES': [],
 'RECIPE_CACHE_DIR': '/Users/brandonfriess/Library/AutoPkg/Cache/com.foo.autopkg.flycut.download',
 'RECIPE_DIR': '/Users/brandonfriess/autopkg/Flycut',
 'RECIPE_OVERRIDE_DIRS': ['/Users/brandonfriess/cpe/autopkg/overrides'],
 'RECIPE_PATH': '/Users/brandonfriess/autopkg/Flycut/Flycut.download.recipe',
 'RECIPE_REPOS': {'/Users/Shared/RecipeRepos/com.foo.corp.git.internal.autopkg': {'URL': 'https://git.corp.foo.com/foo-internal/autopkg.git'}},
 'RECIPE_REPO_DIR': '/Users/Shared/RecipeRepos',
 'RECIPE_SEARCH_DIRS': ['/Users/brandonfriess/cpe/autopkg/overrides,',
                        '/Users/Shared/RecipeRepos/com.foo.corp.git.internal.autopkg'],
 'verbose': 4}
GitHubReleasesInfoProvider
{'Input': {'github_repo': 'TermiT/Flycut'}}
GitHubReleasesInfoProvider: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
GitHubReleasesInfoProvider: No value supplied for GITHUB_URL, setting default value of: https://api.github.com
GitHubReleasesInfoProvider: No value supplied for GITHUB_TOKEN_PATH, setting default value of: ~/.autopkg_gh_token
GitHubReleasesInfoProvider: Selected asset 'Flycut.1.9.4.zip' from release '1.9.4'
{'Output': {'release_notes': '- Removed sandboxing\r\n'
                             '- Made search case-insensitive',
            'url': 'https://github.com/TermiT/Flycut/releases/download/1.9.4/Flycut.1.9.4.zip',
            'version': '1.9.4'}}
```

**AutoPkg run with internal GitHub**
```
$: ./autopkg run --ignore-parent-trust-verification-errors /Users/brandonfriess/contoso/autopkg/fooapp/fooapp.download.recipe -vvvv
Processing /Users/brandonfriess/contoso/autopkg/fooapp/fooapp.download.recipe...
{'AUTOPKG_VERSION': '2.1.1',
 'FAIL_RECIPES_WITHOUT_TRUST_INFO': True,
 'GITHUB_REPO': 'contoso-internal/fooapp',
 'MUNKI_REPO': '/Users/brandonfriess/contoso/munki-mac-packages/public',
 'NAME': 'fooapp',
 'PARENT_RECIPES': [],
 'RECIPE_CACHE_DIR': '/Users/brandonfriess/Library/AutoPkg/Cache/com.contoso.autopkg.fooapp.download',
 'RECIPE_DIR': '/Users/brandonfriess/contoso/autopkg/fooapp',
 'RECIPE_OVERRIDE_DIRS': ['/Users/brandonfriess/contoso/cpe/autopkg/overrides'],
 'RECIPE_PATH': '/Users/brandonfriess/contoso/autopkg/fooapp/fooapp.download.recipe',
 'RECIPE_REPOS': {'/Users/Shared/RecipeRepos/com.contoso.corp.git.contoso-internal.autopkg': {'URL': 'https://git.corp.contoso.com/contoso-internal/autopkg.git'}},
 'RECIPE_REPO_DIR': '/Users/Shared/RecipeRepos',
 'RECIPE_SEARCH_DIRS': ['/Users/brandonfriess/contoso/cpe/autopkg/overrides,',
                        '/Users/Shared/RecipeRepos/com.contoso.corp.git.contoso-internal.autopkg'],
 'verbose': 4}
com.contoso.autopkg.shared/AbsPath
{'Input': {'relative_path': '~/.contosoproxy'}}
AbsPath: /Users/brandonfriess/.contosoproxy
{'Output': {'absolute_path': '/Users/brandonfriess/.contosoproxy'}}
GitHubReleasesInfoProvider
{'Input': {'GITHUB_TOKEN_PATH': '~/.contoso_autopkg_github_token',
           'GITHUB_URL': 'http://git.corp.contoso.com/api/v3',
           'curl_opts': ['--unix-socket', '/Users/brandonfriess/.contosoproxy'],
           'github_repo': 'contoso-internal/fooapp'}}
GitHubReleasesInfoProvider: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
GitHubReleasesInfoProvider: Selected asset 'fooapp.authn_bundle' from release 'fooapp v2.0.3'
{'Output': {'release_notes': 'Reminder: We publish authn signed bundles. In '
                             'order to verify the signature and\r\n'
                             'extract a usable original binary from the authn '
                             'bundle use `bin/verify`.\r\n'
                             '\r\n'
                             '```\r\n'
                             '$ sha256sum *\r\n'
                             'c8cb12a357a160bddd92283235dbf84104f1959aff2f655943c07f5274dcb451  '
                             'fooapp\r\n'
                             '4b3b28b931aa70cec2532c53f6fa3a7d9afc37663631f554b2fdb95e7b80f50f  '
                             'fooapp.authn_bundle\r\n'
                             '```',
            'url': 'https://git.corp.contoso.com/contoso-internal/fooapp/releases/download/v2.0.3/certproxy.authn_bundle',
            'version': '2.0.3'}}
EndOfCheckPhase
```

Excerpt of recipe Input for internal Github:
```
        <dict>
            <key>Arguments</key>
            <dict>
                <key>github_repo</key>
                <string>%GITHUB_REPO%</string>
                <key>curl_opts</key>
                <array>
                    <string>--unix-socket</string>
                    <string>%absolute_path%</string>
                </array>
                <key>GITHUB_URL</key>
                <string>http://git.corp.contoso.com/api/v3</string>
                <key>GITHUB_TOKEN_PATH</key>
                <string>~/.contoso_autopkg_github_token</string>
            </dict>
            <key>Processor</key>
            <string>GitHubReleasesInfoProvider</string>
        </dict>
```

Thanks for considering this!

### CODE REVIEW

**Comment by bfreezy** [comment]
Well this timing is interesting! A couple hours later https://github.com/autopkg/autopkg/pull/645 landed, which would break this feature. If the maintainers want to consider adding this, we'll have to work through how we want to land the changes.

**Comment by linuxfood** [comment]
> Well this timing is interesting! A couple hours later #645 landed, which would break this feature. If the maintainers want to consider adding this, we'll have to work through how we want to land the changes.

Interesting indeed!

I quickly skimmed your changes. I don't think the changes are mutually exclusive. It will require some adjustments in one of the PRs, but I don't think they go in incompatible directions. If one of us waits for the other PR to land, rebasing and making the appropriate modifications would appear to be relatively straight forward. Do you have reason to think they'll be more involved?

**Comment by bfreezy** [comment]
I don't think it will be more involved, no. I mainly wanted to call out both of our PR's so we could all be on the same page 🙂

**Comment by nmcspadden** [comment]
I just merged in a different PR, which means this one needs to be rebased.

**Comment by bfreezy** [comment]
Apologies all. I have made a mess of this PR with my rebase. Going to close this and open a new PR.

**Pull request closed without merging**
