### PR TITLE
Fix handling of scp syntax for git urls

### PR DESCRIPTION
**Pull request by choules**
These changes fix some problems already mentioned in Issue #276. Using the common scp syntax for git urls was not properly processed.

We convert those kind of urls to a proper ssh url, so that

`autopkg repo-add git@privategitserver:namespace/repo.git`

is actually equivalent to

`autopkg repo-add ssh://git@privategitserver/namespace/repo.git`

Furthermore we are removing the username – if present – from the url, to keep the directory path free from (probably unwanted) "@" characters.

### CODE REVIEW

**Comment by nmcspadden** [comment]
This is neat, I like it. Can you please show the output of autopkg repo-add using both this syntax, and a regular pattern (such as "recipes" or "nmcspadden-recipes") to show that it works with your changes?

**Comment by choules** [comment]
Nice catch, @nmcspadden. I definitely need to gain more experience with Python. It should work correctly now.

**Comment by nmcspadden** [comment]
Please change the target of this over to the dev branch, thanks. Then I'll merge.

**Comment by choules** [comment]
Done.

**Pull request merged**
