### PR TITLE
add automated UnitTests for AutoPkg with GitHub Actions

### PR DESCRIPTION
**Pull request by jgstew**
automatically run unittests on pull request or push

### CODE REVIEW

**Comment by jgstew** [comment]
This is now working to run unittests and partial e2e tests automatically on MacOS and Ubuntu: https://github.com/jgstew/autopkg/actions/runs/2145502297

**Comment by jgstew** [comment]
automated unittests on windows are not currently working as seen here: https://github.com/jgstew/autopkg/runs/5964138026?check_suite_focus=true

**Comment by jgstew** [comment]
This didn't work to fix the windows signtool missing issue:

```
env:
  # https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/SignToolVerifier.py#L65
  # https://github.com/Dana-Prajea/code-sign-action/blob/98c79121b376beab8d6a9484f445089db4461bca/index.ts#L11
  signtool_path: "C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe"
```

**Comment by jgstew** [comment]
github hosted windows action runners do have signtool.exe on them but not in the place the processor is looking for them it seems:

Run Get-ChildItem -Path "C:/Program Files (x86)/Windows Kits" -Filter signtool.exe -Recurse -ErrorAction SilentlyContinue -Force

```
    Directory: C:\Program Files (x86)\Windows Kits\10\App Certification Kit

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           9/12/2021  2:47 AM         459208 signtool.exe

    Directory: C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          10/23/2018  2:10 AM         418856 signtool.exe

    Directory: C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x86

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           9/12/2021  2:48 AM         467408 signtool.exe

    Directory: C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x64

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           9/12/2021  2:47 AM         459216 signtool.exe

    Directory: C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x86
```

**Comment by jgstew** [comment]
I had to add a new default path option for signtool.exe to fix unittests on github hosted action runners for windows, but now all unittests are working.

**Comment by nmcspadden** [comment]
Wow, this is fantastic work! I'm waiting for the tests to finish queueing and then if all looks good, we'll try and merge it!

**Comment by jgstew** [comment]
all good now. I tried to create a recipe yaml file on the fly and run it as an integration test, but it didn't work... the file creation part. Trying again over here: https://github.com/jgstew/jgstew-recipes/blob/main/.github/workflows/AutoPkgCoreProcessors.yaml

**Comment by jgstew** [comment]
sweet, integration test recipe created on the fly in the github action is working.

Basically I am doing the e2e tests and an integration recipe that covers all of those that are cross platform, not the full possible set.

In the future it would be possible to have additional steps that would run the macos only e2e steps only on macos and further integration tests that are platform specific only on that platform, but for now, just focusing on those that are cross platform.

**Comment by jgstew** [comment]
I added some comments to the github action, no code changes.

**Comment by nmcspadden** [comment]
I'm cool to merge this, but open question:
Should the test recipe just be a static yaml file in the tests folder? That feels a little less fragile and easier to maintain than having it be echoed out as part of the action.

What do you all think?

**Comment by grahampugh** [comment]
@nmcspadden yes, makes sense to have it as a real recipe. I assume the test is restricted to cross-platform-able processors, and deliberately avoiding some tests like disk image mounting?

**Comment by jgstew** [comment]
@nmcspadden I agree that it makes sense to have the e2e tests and the recipe be static files in the test folder, but I'm currently using a version of the e2e tests that only use cross platform processors, and some others that don't work well in github actions.

The recipe this is using I just put in this PR over here: https://github.com/autopkg/recipes/pull/423

But maybe this cross platform recipe belongs in the tests folder in autopkg/autopkg instead?

**Comment by nmcspadden** [comment]
> But maybe this cross platform recipe belongs in the tests folder in autopkg/autopkg instead?

That's what I would suggest. Put it in this repo, in the tests folder, not as a regular recipe in a recipe repo.

**Comment by jgstew** [comment]
I guess I wonder why not merge this PR and I can switch it to use a recipe in the folder later?

**Comment by jgstew** [comment]
@nmcspadden I have made the requested change.

**Pull request merged**
