### PR TITLE
Add support for a GitHub or BitBucket repo's SSH URL 

### PR DESCRIPTION
**Pull request by eahrold**
This treats strings prefixed with `git@` as a valid clone URL.

Additionally I extracted the checks that use urlparse() into a new `valid_repo_url()` function.
The one difference I noticed was that in the `expand_repo_url()` func the scheme was checked, where as in `get_repo_info()` netloc was checked. 

They seem to both be used to validate a string as a URL, but there may be an aspect you've thought through that I'm missing. I can roll that back if need be.

### CODE REVIEW

**Comment by gregneagle** [comment]
Aren't the SSH URLs more properly written: `ssh://git@github.com/path/to/repo`?

If we're going to support the alternative SSH URL syntax described in `git clone --help`, why limit it to URLs that start with `git@` ?  That's certainly not a requirement of the syntax.

**Comment by eahrold** [comment]
`ssh://git@github.com...` would work anyway since that breaks up correctly with urlparse().
This just additionally adds support for `git@...` as a url, as advertised by GitHub/BitBucket.

ssh-url

Taking a close look, however, a reverse domain for the local path isn't constructed correctly as a reverse domain in either case due to the `@git` I'll tackle that next.

**Comment by gregneagle** [comment]
So we either tell people to use the ssh:// syntax, or we implement "correct" support for the alternative syntax, in which "git@" is not special.

**Comment by eahrold** [comment]
So a generic _user@_ ?

**Comment by gregneagle** [comment]
Quoting from the output of `git clone --help`:

```
An alternative scp-like syntax may also be used with the ssh protocol:

       o   [user@]host.xz:path/to/repo.git/

       This syntax is only recognized if there are no slashes before the first colon. This helps differentiate a local path that contains a colon. For example the local
       path foo:bar could be specified as an absolute path or ./foo:bar to avoid being misinterpreted as an ssh url.
```

Notice that the `user@` part is _optional_!

**Comment by eahrold** [comment]
@gregneagle,  This PR should now support full implementation of all clone syntax listed in `git clone --help`. Let me know if you have any other concerns. Thanks.

**Comment by eahrold** [comment]
💀

**Pull request closed without merging**
