### PR TITLE
Autopkg exit codes

### PR DESCRIPTION
**Pull request by nmcspadden**
`autopkg run` now returns 1 if any recipe failed, rather than returning the number of recipes that failed.

### CODE REVIEW

**Comment by gregneagle** [comment]
OK, that's a good start. Have you checked to see if there are any other situations that result in a exit result == 1?

**Comment by timsutton** [comment]
I've found `1` happen in other scenarios as well, that's why I recommend (had just posted a [comment](https://github.com/autopkg/autopkg/issues/296#issuecomment-232736730) as Nick opened this PR) we could pick a different number for this specific case.

**Comment by nmcspadden** [comment]
What would your preferred exit code be for 'some recipe failed'?

**Comment by gregneagle** [comment]
None of these:
http://www.tldp.org/LDP/abs/html/exitcodes.html

**Comment by nmcspadden** [comment]
So, 3 then?

**Comment by timsutton** [comment]
At one point MagerValp pointed me to a good set of them, but I just found the Python `os` module reference to have a decent list of typical user-defined ones: https://docs.python.org/2/library/os.html#os.EX_OK

My understanding is that there's a precedent of starting at 64, but presumably you'd also use some of those things for other issues like wrong command arguments, file access, etc.

**Comment by gregneagle** [comment]
Propose it. See if people object.

**Comment by nmcspadden** [comment]
Based on @timsutton's suggestion, I think https://docs.python.org/2/library/os.html#os.EX_SOFTWARE is an appropriate choice to use, as there was an internal failure by a recipe failing to run properly.

**Comment by gregneagle** [comment]
Or os.EX_CANTCREAT because the recipe failed to create the desired output file..

**Comment by timsutton** [comment]
I'm not really arguing it should be one of those specific ones in that list, either - we've got plenty of "room" for more codes above the ones conveniently defined in `os`. If we see it being useful to be able to specifically distinguish this scenario of having a successful run but with failures, we can also pick a code that we won't ever use anywhere else.

**Comment by natewalck** [comment]
I like the idea of knowing how many recipes failed just from the exit code. Maybe 201 = 1 recipe failed, 202 = 2 failed, etc?

Trying to get it out of range of standard exit codes, but that could get near 255+ then.

I like -1 for autopkg died and 0 for run was successfully.

**Comment by nmcspadden** [comment]
To be honest, I really don't particularly care either way.  I don't really care what exit code it gets. I just want to distinguish "autopkg crashed" vs. literally any other outcome. If we want to distinguish different kinds of crashes, that's fine too, but that's not what I want to fix right now - that's something we can work on in a separate issue. 

The immediate issue is that there's no exit code distinction between "I crashed" and "I failed exactly 1 recipe", and that's what needs to be solved because otherwise wrapping `autopkg run` becomes a real challenge.

As per https://github.com/autopkg/autopkg/issues/296#issuecomment-232748783 as well, I also don't mind the return code being 'number of recipes that failed' so long as every occurrence of autopkg crashing is caught and returns something other than 1.  That seems like it's a bit harder and longer to solve, and in the meantime, the original problem still exists.  Can we guarantee that we can catch autopkg faulting and return -1 in each case?

**Comment by timsutton** [comment]
I think if you want more details on how many recipes failed then you go get a list of failures from the report plist.

I also don't really care what exit code it gets, but I think if we're going to talk about modifying how AutoPkg reports exit status we should make a change we can stick with (since this is something consumed and relied upon in wrapper scripts, etc.).

Right now you'll get a `1` on pretty much any crash as far as I know, which is the catch-all error. In the future we could use some of the other more specific user errors defined in `os` if we want to be good UNIX citizens. Those ones go up to around 78.

What if we just round up and say 80? We can reserve this to be specific for a run completion but with one or more recipe failures. I think we should put this in as a commented constant somewhere rather than burying it in the function, though.

**Comment by nmcspadden** [comment]
Would you prefer that constant be defined in autopkglib, or is it safe enough in autopkg itself?

**Comment by timsutton** [comment]
Eventually maybe more of `autopkg` can be refactored elsewhere to make it more manageable, but for now all the logic of the tool itself is pretty self-contained, so might as well put error code(s) in `autopkg` too for the time being.

**Comment by timsutton** [comment]
Working here. I noticed that if a recipe can't be found, and AutoPkg falls back to an interactive search prompt (and I say no), that must also be treated like a failure and results in the same exit code.

It's simplest to just assume that's also a recipe failure (you can argue it is, since the search operation for this recipe doesn't start until we actually "arrive" at this recipe in the run).

**Pull request merged**
