### PR TITLE
Urldownloader content encoding

### PR DESCRIPTION
**Pull request by jessepeterson**
PR for autopkg/autopkg#126. Feedback welcome!

### CODE REVIEW

**Comment by timsutton** [comment]
Looks ok to me on first glance - are your Extensis recipes still an example of ones which would benefit from supporting gzip Content-Encodings in URLDownloader?

**Comment by jessepeterson** [comment]
Yes, the UniversalTypeClient4 is. Today, anyway. :)

**Comment by timsutton** [comment]
I've merged (with a couple small nitpicks) and tested it my usual run of about 50-60 recipes. Anyway, as far as impact to all other recipes, if the servers aren't sending back `Content-Encoding` response headers, then the gzip code paths aren't executed.

I'm curious why you set `gzip_handle = zlib.decompressobj(16 + zlib.MAX_WBITS)`? How'd you arrive at that magic number (32?)

If I leave it to the default it seems too small, and I can't make it too big either. The default is 16, according to docs.

**Comment by jessepeterson** [comment]
As far as I understand it makes it decode strictly gzip streams. Per the [zlib docs](http://www.zlib.net/manual.html#inflateInit2):

> windowBits can also be greater than 15 for optional gzip decoding. Add 32 to windowBits to enable zlib and gzip decoding with automatic header detection, or add 16 to decode only the gzip format (the zlib format will return a Z_DATA_ERROR). If a gzip stream is being decoded, strm->adler is a crc32 instead of an adler32.

I don't see it merged yet in main tree? Or are you saying you just merged it yourself locally for your testing? I, too, have around 50-60 recipes that seem to run just fine using this code.

**Comment by timsutton** [comment]
Ah, ok. I had not gone so far as zlib's docs, only read the docs for the Python module. I'll add an explanation to the code and push the updated merge.

**Pull request merged**
