### PR TITLE
Use curl for GitHub API calls instead of urllib2

### PR DESCRIPTION
**Pull request by hjuutilainen**
These changes swap out urllib2 for curl when making GitHub API calls. I tried to keep changes to existing behaviour at minimum but some things are different:

- When using curl, we can't easily get the HTTP status code. I therefore removed the status code from the `call_api()` return value and just return the json response.
- When doing `autopkg search -t`, we're not trying to create a new token over the GH API. Instead just display a link where a token can be manually created and wait for user to copy/paste it back in.

This PR doesn't include any changes to the token behaviour, that will be a separate PR.

### CODE REVIEW

**Comment by gregneagle** [comment]
I'm curious why you say you can't easily get the http status code. Back when Munki was using curl, this code did get http status. Maybe it can help?
https://github.com/munki/munki/blob/Munki1/code/client/munkilib/fetch.py#L91-L427

**Comment by gregneagle** [comment]
This code is similar: https://github.com/wdas/reposado/blob/master/code/repo_sync#L265-L453

**Comment by hjuutilainen** [comment]
I’ll take a look at those if there’s something we can reuse. What I meant with easily was not having to write a few hundred lines of new code for this issue.

**Comment by gregneagle** [comment]
...which is why I pointed you at some "tested"/not-new code... :-)

**Comment by gregneagle** [comment]
I'll leave it to you decide if the need for/lack of the http status code is important enough to deal with at this time, and trust your decision in this. Feel free to merge the code when you are happy/confident.

**Comment by macmule** [comment]
Not sure if this is of any help, it's a snippet from one of our things & will get the HTTP code

```
    curl_args = ['/usr/bin/curl', '-s', '-w', ' %{http_code} %{url_effective}', \
                                             '-d', jwt_complete, ENVQUERY_URL,]
    try:
        curl_output = subprocess.check_output(curl_args)
    except (subprocess.CalledProcessError, NameError) as error_msg:
        print 'ERROR: lookup with: %s' % error_msg
        sys.exit(1)

    try:
        return_code = curl_output.split()[0]
        end_url = curl_output.split()[1]
    except (ValueError, IndexError):
        print 'ERROR: invalid response: %s' % curl_output
        sys.exit(1)

    if end_url != SOME_URL:
        print 'ERROR: URL redirected: %s' % curl_output
        sys.exit(1)
    else:
        pass

    if return_code != '204':
        print 'ERROR: error response code: %s' % return_code
        sys.exit(1)
    else:
        pass
```

**Comment by gregneagle** [comment]
So this includes https://github.com/autopkg/autopkg/pull/407 ?

We should get a 1.0.4 release candidate out ASAP since this affects a great number of autopkg users.

**Comment by hjuutilainen** [comment]
Yes, #407 is included.

**Comment by hjuutilainen** [comment]
I’ve run all of my own AutoPkg workflows with a couple of hundred recipes using this code and had no problems. I think this is good to go.

**Comment by gregneagle** [comment]
Merge it!

**Comment by hjuutilainen** [comment]
Merged now.

**Pull request merged**
