### PR TITLE
allow `-` in the package version as it is  allowed in MacOS

### LINKED ISSUE #641: PkgCreator chokes on valid version number
**Describe the problem**
Building a package for "Appium-1.1.17-1" and I get the error: `Error in local.pkg.Appium: Processor: PkgCreator: Error: Invalid version component "1-1"` That version number parses fine with semantic versioning and package.version.parse.

Looking for the error text I find that it's come from `autopkgserver` `packager.py` line 233 and that the component `1-1` fails the regular expression defined in line 34: `re_version = re.compile(r"^[a-z0-9_ ]*[0-9][a-z0-9_ ]*$", re.I)`

BTW - the parent recipe is `com.github.blackthroat.download.Appium`, here's the PkgCreator block.

```
<key>Processor</key>
<string>PkgCreator</string>
<key>Arguments</key>
<dict>
    <key>pkgname</key>
    <string>%NAME%-%version%</string>
    <key>pkg_request</key>
    <dict>
        <key>pkgdir</key>
        <string>%RECIPE_CACHE_DIR%</string>
        <key>id</key>
        <string>%PKG_ID%</string>
        <key>options</key>
        <string>purge_ds_store</string>
        <key>chown</key>
        <array>
            <dict>
                <key>path</key>
                <string>Applications</string>
                <key>user</key>
                <string>root</string>
                <key>group</key>
                <string>admin</string>
            </dict>
        </array>
    </dict>
</dict>
```

**Preferences contents**
Just my repo list. 
```
https://github.com/autopkg/recipes
https://github.com/autopkg/rtrouton-recipes
https://github.com/autopkg/hansen-m-recipes
https://github.com/autopkg/hjuutilainen-recipes
https://github.com/autopkg/homebysix-recipes
https://github.com/autopkg/moofit-recipes
https://github.com/autopkg/rderewianko-recipes
https://github.com/autopkg/dataJAR-recipes
https://github.com/autopkg/HobbitHardcase-recipes
https://github.com/autopkg/novaksam-recipes
https://github.com/autopkg/justinrummel-recipes
https://github.com/autopkg/keeleysam-recipes
https://github.com/autopkg/arubdesu-recipes
https://github.com/autopkg/gregneagle-recipes
https://github.com/autopkg/fishd72-recipes
https://github.com/autopkg/mosen-recipes
https://github.com/autopkg/blackthroat-recipes
https://github.com/autopkg/chilcote-recipes
https://github.com/autopkg/MichalMMac-recipes
https://github.com/autopkg/valdore86-recipes
https://github.com/autopkg/aysiu-recipes
https://github.com/autopkg/jleggat-recipes
https://github.com/facebook/Recipes-for-AutoPkg
https://github.com/autopkg/grahampugh-recipes
https://github.com/autopkg/48kRAM-recipes
https://github.com/autopkg/foigus-recipes
https://github.com/autopkg/adobe-ccp-recipes
https://github.com/autopkg/n8felton-recipes
https://github.com/autopkg/tbridge-recipes
```
(That's in search order).
**AutoPkg output**
```
autopkg run Appium.pkg
Processing Appium.pkg...
Invalid version component "1-1"
Failed.

The following recipes failed:
    Appium.pkg
        Error in local.pkg.Appium: Processor: PkgCreator: Error: Invalid version component "1-1"

Nothing downloaded, packaged or imported.
```

**Expected behavior**
A nice built package called "Appium-1.17.1-1.pkg"

**Version (please complete the following information):**
 - OS version: 10.15.6
- AutoPkg Version: 2.1

### PR DESCRIPTION
**Pull request by gfa**
Fixes #641

### CODE REVIEW

**Comment by gfa** [comment]
with `-`

```
{'AUTOPKG_VERSION': u'1.4.1',
 u'DISPLAY_NAME': u'package',
 u'MUNKI_REPO': u'/opt/munki',
 u'MUNKI_REPO_SUBDIR': u'apps/net.example.package',
 u'NAME': u'net.example.package',
 'PARENT_RECIPES': ['/Users/username/devel/munki-autopkg/net.example.package/net.example.package.download.recipe'],
 'RECIPE_CACHE_DIR': u'/Users/username/Library/AutoPkg/Cache/net.example.package.munki',
 'RECIPE_DIR': '/Users/username/devel/munki-autopkg/net.example.package',
 'RECIPE_OVERRIDE_DIRS': ['~/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': '/Users/username/devel/munki-autopkg/net.example.package/net.example.package.munki.recipe',
 'RECIPE_SEARCH_DIRS': ['.',
                        '~/Library/AutoPkg/Recipes',
                        '/Library/AutoPkg/Recipes',
                        '/Users/username/devel/munki-autopkg/net.example.package'],
 u'pkginfo': {
    catalogs =     (
        "catalog_stable"
    );
    category = Utilities;
    description = "This build is only for development purposes. _Do not_ distribute outside Example";
    "display_name" = package;
    "installable_condition" = "package == \"true\"";
    name = "net.example.package";
},
 'verbose': 3,
 u'version': u'%version%'}
URLTextSearcher
{'Input': {'re_pattern': u'package.RELEASE.([0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}-[0-9]{2}-[0-9]{2}Z)',
           'result_output_var_name': u'version',
           'url': u'https://url/server/package/release/darwin-amd64'}}
URLTextSearcher: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
URLTextSearcher: Found matching text (version): 2021-05-11T23-27-41Z
{'Output': {u'version': '2021-05-11T23-27-41Z'}}
URLDownloader
{'Input': {'CURL_PATH': '/usr/bin/curl',
           'filename': u'net.example.package-2021-05-11T23-27-41Z',
           'url': u'https://url/server/package/release/darwin-amd64/package.RELEASE.2021-05-11T23-27-41Z'}}
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/username/Library/AutoPkg/Cache/net.example.package.munki/downloads/net.example.package-2021-05-11T23-27-41Z
{'Output': {'pathname': u'/Users/username/Library/AutoPkg/Cache/net.example.package.munki/downloads/net.example.package-2021-05-11T23-27-41Z'}}
PkgRootCreator
{'Input': {'pkgdirs': {
    usr = 0755;
    "usr/local" = 0755;
    "usr/local/bin" = 0755;
},
           'pkgroot': u'/Users/username/Library/AutoPkg/Cache/net.example.package.munki/root'}}
PkgRootCreator: Created /Users/username/Library/AutoPkg/Cache/net.example.package.munki/root
PkgRootCreator: Creating usr
PkgRootCreator: Created /Users/username/Library/AutoPkg/Cache/net.example.package.munki/root/usr
PkgRootCreator: Creating usr/local
PkgRootCreator: Created /Users/username/Library/AutoPkg/Cache/net.example.package.munki/root/usr/local
PkgRootCreator: Creating usr/local/bin
PkgRootCreator: Created /Users/username/Library/AutoPkg/Cache/net.example.package.munki/root/usr/local/bin
{'Output': {}}
Copier
{'Input': {'destination_path': u'/Users/username/Library/AutoPkg/Cache/net.example.package.munki/root/usr/local/bin/package',
           'overwrite': u'true',
           'source_path': u'/Users/username/Library/AutoPkg/Cache/net.example.package.munki/downloads/net.example.package-2021-05-11T23-27-41Z'}}
Copier: Copied /Users/username/Library/AutoPkg/Cache/net.example.package.munki/downloads/net.example.package-2021-05-11T23-27-41Z to /Users/username/Library/AutoPkg/Cache/net.example.package.munki/root/usr/local/bin/package
{'Output': {}}
net.example.processors.ReadPlist/ReadPlist
{'Input': {'plist_keys': {
    InternalVersion = intversion;
},
           'plist_path': u'/Users/username/devel/munki-autopkg/net.example.package/_config'}}
ReadPlist: Assigning value of '1' to output variable 'intversion'
{'Output': {'readplist_output_variables': {u'intversion': 1}}}
PkgCreator
{'Input': {'force_pkg_build': u'True',
           'pkg_request': {
    chown =     (
                {
            group = wheel;
            mode = 0755;
            path = "usr/local/bin/package";
            user = root;
        }
    );
    id = "net.example.package";
    options = "purge_ds_store";
    pkgname = "package-2021-05-11T23-27-41Z.1";
    pkgroot = "/Users/username/Library/AutoPkg/Cache/net.example.package.munki/root";
    version = "2021-05-11T23-27-41Z.1";
}}}
PkgCreator: Connecting
PkgCreator: Sending packaging request
PkgCreator: Disconnecting
{'Output': {'new_package_request': True,
            'pkg_creator_summary_result': {'data': {'identifier': u'net.example.package',
                                                    'pkg_path': '/Users/username/Library/AutoPkg/Cache/net.example.package.munki/package-2021-05-11T23-27-41Z.1.pkg',
                                                    'version': u'2021-05-11T23-27-41Z.1'},
                                           'report_fields': ['identifier',
                                                             'version',
                                                             'pkg_path'],
                                           'summary_text': 'The following packages were built:'},
            'pkg_path': '/Users/username/Library/AutoPkg/Cache/net.example.package.munki/package-2021-05-11T23-27-41Z.1.pkg'}}
net.example.processors.MakeManifests/MakeManifests
{'Input': {'manifests': {
    "manifest_stable" =     (
        "optional_installs"
    );
}}}
{'Output': {}}
net.example.processors.MunkiImporter/MunkiImporter
{'Input': {'MUNKI_REPO': u'/opt/munki',
           'pkg_path': u'/Users/username/Library/AutoPkg/Cache/net.example.package.munki/package-2021-05-11T23-27-41Z.1.pkg',
           'pkginfo': {
    catalogs =     (
        "catalog_stable"
    );
    category = Utilities;
    description = "This build is only for development purposes. _Do not_ distribute outside Example";
    "display_name" = package;
    "installable_condition" = "package == \"true\"";
    name = "net.example.package";
}}}
MunkiImporter: Item package-2021-05-11T23-27-41Z.1.pkg already exists in the munki repo as pkgs/package-2021-05-11T23-27-41Z.1.pkg.
{'Output': {'pkg_repo_path': u'/opt/munki/pkgs/package-2021-05-11T23-27-41Z.1.pkg'}}
{'AUTOPKG_VERSION': u'1.4.1',
 'CHECK_FILESIZE_ONLY': False,
 'CURL_PATH': '/usr/bin/curl',
 u'DISPLAY_NAME': u'package',
 u'MUNKI_REPO': u'/opt/munki',
 u'MUNKI_REPO_SUBDIR': u'apps/net.example.package',
 u'NAME': u'net.example.package',
 'PARENT_RECIPES': ['/Users/username/devel/munki-autopkg/net.example.package/net.example.package.download.recipe'],
 'RECIPE_CACHE_DIR': u'/Users/username/Library/AutoPkg/Cache/net.example.package.munki',
 'RECIPE_DIR': '/Users/username/devel/munki-autopkg/net.example.package',
 'RECIPE_OVERRIDE_DIRS': ['~/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': '/Users/username/devel/munki-autopkg/net.example.package/net.example.package.munki.recipe',
 'RECIPE_SEARCH_DIRS': ['.',
                        '~/Library/AutoPkg/Recipes',
                        '/Library/AutoPkg/Recipes',
                        '/Users/username/devel/munki-autopkg/net.example.package'],
 u'destination_path': u'/Users/username/Library/AutoPkg/Cache/net.example.package.munki/root/usr/local/bin/package',
 'download_changed': False,
 'etag': '',
 u'filename': u'net.example.package-2021-05-11T23-27-41Z',
 u'force_pkg_build': u'True',
 u'intversion': '1',
 'last_modified': '',
 u'manifests': {
    "manifest_stable" =     (
        "optional_installs"
    );
},
 'munki_info': {},
 'munki_repo_changed': False,
 'new_package_request': True,
 u'overwrite': u'true',
 'pathname': u'/Users/username/Library/AutoPkg/Cache/net.example.package.munki/downloads/net.example.package-2021-05-11T23-27-41Z',
 'pkg_creator_summary_result': {'data': {'identifier': u'net.example.package',
                                         'pkg_path': '/Users/username/Library/AutoPkg/Cache/net.example.package.munki/package-2021-05-11T23-27-41Z.1.pkg',
                                         'version': u'2021-05-11T23-27-41Z.1'},
                                'report_fields': ['identifier',
                                                  'version',
                                                  'pkg_path'],
                                'summary_text': 'The following packages were built:'},
 'pkg_path': u'/Users/username/Library/AutoPkg/Cache/net.example.package.munki/package-2021-05-11T23-27-41Z.1.pkg',
 'pkg_repo_path': u'/opt/munki/pkgs/package-2021-05-11T23-27-41Z.1.pkg',
 u'pkg_request': {
    chown =     (
                {
            group = wheel;
            mode = 0755;
            path = "usr/local/bin/package";
            user = root;
        }
    );
    id = "net.example.package";
    infofile = "";
    options = "purge_ds_store";
    pkgdir = "/Users/username/Library/AutoPkg/Cache/net.example.package.munki";
    pkgname = "package-2021-05-11T23-27-41Z.1";
    pkgroot = "/Users/username/Library/AutoPkg/Cache/net.example.package.munki/root";
    pkgtype = flat;
    resources = "";
    scripts = "";
    version = "2021-05-11T23-27-41Z.1";
},
 u'pkgdirs': {
    usr = 0755;
    "usr/local" = 0755;
    "usr/local/bin" = 0755;
},
 u'pkginfo': {
    catalogs =     (
        "catalog_stable"
    );
    category = Utilities;
    description = "This build is only for development purposes. _Do not_ distribute outside Example";
    "display_name" = package;
    "installable_condition" = "package == \"true\"";
    name = "net.example.package";
},
 'pkginfo_repo_path': '',
 u'pkgroot': u'/Users/username/Library/AutoPkg/Cache/net.example.package.munki/root',
 u'plist_keys': {
    InternalVersion = intversion;
},
 u'plist_path': u'/Users/username/devel/munki-autopkg/net.example.package/_config',
 'prefetch_filename': False,
 u're_pattern': u'package.RELEASE.([0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}-[0-9]{2}-[0-9]{2}Z)',
 'readplist_output_variables': {u'intversion': 1},
 u'result_output_var_name': u'version',
 u'source_path': u'/Users/username/devel/munki-autopkg/net.example.package/_config',
 u'url': u'https://url/server/package/release/darwin-amd64/package.RELEASE.2021-05-11T23-27-41Z',
 'verbose': 3,
 u'version': '2021-05-11T23-27-41Z'}
Receipt written to /Users/username/Library/AutoPkg/Cache/net.example.package.munki/receipts/net.example.package.munki-receipt-20210512-094750.plist

The following packages were built:
    Identifier       Version                 Pkg Path                                                                                      
    ----------       -------                 --------                                                                                      
    net.example.package  2021-05-11T23-27-41Z.1  /Users/username/Library/AutoPkg/Cache/net.example.package.munki/package-2021-05-11T23-27-41Z.1.pkg  

```

**Comment by gfa** [comment]
package version without `-`

```
{'AUTOPKG_VERSION': u'1.4.1',
 u'DISPLAY_NAME': u'package',
 u'MUNKI_REPO': u'/opt/munki',
 u'MUNKI_REPO_SUBDIR': u'apps/net.example.package',
 u'NAME': u'net.example.package',
 'PARENT_RECIPES': ['/Users/username/devel/munki-autopkg/net.example.package/net.example.package.download.recipe'],
 'RECIPE_CACHE_DIR': u'/Users/username/Library/AutoPkg/Cache/net.example.package.munki',
 'RECIPE_DIR': '/Users/username/devel/munki-autopkg/net.example.package',
 'RECIPE_OVERRIDE_DIRS': ['~/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': '/Users/username/devel/munki-autopkg/net.example.package/net.example.package.munki.recipe',
 'RECIPE_SEARCH_DIRS': ['.',
                        '~/Library/AutoPkg/Recipes',
                        '/Library/AutoPkg/Recipes',
                        '/Users/username/devel/munki-autopkg/net.example.package'],
 u'pkginfo': {
    catalogs =     (
        "catalog_stable"
    );
    category = Utilities;
    description = "Package - A tool";
    "display_name" = package;
    "installable_condition" = "tag == \"true\"";
    name = "net.example.package";
},
 'verbose': 3,
 u'version': u'%version%'}
URLTextSearcher
{'Input': {'re_pattern': u'package-v([0-9\\.]+).darwin.x86_64.tar.xz',
           'result_output_var_name': u'version',
           'url': u'https://github.com/user/package/releases'}}
URLTextSearcher: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
URLTextSearcher: Found matching text (version): 0.7.2
{'Output': {u'version': '0.7.2'}}
URLDownloader
{'Input': {'CURL_PATH': '/usr/bin/curl',
           'filename': u'net.example.package-0.7.2.tar.xz',
           'url': u'https://github.com/user/package/releases/download/v0.7.2/package-v0.7.2.darwin.x86_64.tar.xz'}}
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/username/Library/AutoPkg/Cache/net.example.package.munki/downloads/net.example.package-0.7.2.tar.xz
{'Output': {'pathname': u'/Users/username/Library/AutoPkg/Cache/net.example.package.munki/downloads/net.example.package-0.7.2.tar.xz'}}
PkgRootCreator
{'Input': {'pkgdirs': {
    usr = 0755;
    "usr/local" = 0755;
    "usr/local/bin" = 0755;
},
           'pkgroot': u'/Users/username/Library/AutoPkg/Cache/net.example.package.munki/root'}}
PkgRootCreator: Created /Users/username/Library/AutoPkg/Cache/net.example.package.munki/root
PkgRootCreator: Creating usr
PkgRootCreator: Created /Users/username/Library/AutoPkg/Cache/net.example.package.munki/root/usr
PkgRootCreator: Creating usr/local
PkgRootCreator: Created /Users/username/Library/AutoPkg/Cache/net.example.package.munki/root/usr/local
PkgRootCreator: Creating usr/local/bin
PkgRootCreator: Created /Users/username/Library/AutoPkg/Cache/net.example.package.munki/root/usr/local/bin
{'Output': {}}
net.example.processors.CmdShell/CmdShell
{'Input': {'cmd': u'#!/bin/bash\nset -e\ntar -C /Users/username/Library/AutoPkg/Cache/net.example.package.munki -Jxpvf /Users/username/Library/AutoPkg/Cache/net.example.package.munki/downloads/net.example.package-0.7.2.tar.xz\n'}}
package-v0.7.2/LICENSE.txt
package-v0.7.2/README.txt
package-v0.7.2/package

{'Output': {'working_dir': '/Users/username/devel/munki-autopkg'}}
Copier
{'Input': {'destination_path': u'/Users/username/Library/AutoPkg/Cache/net.example.package.munki/root/usr/local/bin/package',
           'overwrite': u'true',
           'source_path': u'/Users/username/Library/AutoPkg/Cache/net.example.package.munki/package-v0.7.2/package'}}
Copier: Copied /Users/username/Library/AutoPkg/Cache/net.example.package.munki/package-v0.7.2/package to /Users/username/Library/AutoPkg/Cache/net.example.package.munki/root/usr/local/bin/package
{'Output': {}}
net.example.processors.ReadPlist/ReadPlist
{'Input': {'plist_keys': {
    InternalVersion = intversion;
},
           'plist_path': u'/Users/username/devel/munki-autopkg/net.example.package/_config'}}
ReadPlist: Assigning value of '1' to output variable 'intversion'
{'Output': {'readplist_output_variables': {u'intversion': 1}}}
PkgCreator
{'Input': {'force_pkg_build': u'True',
           'pkg_request': {
    chown =     (
                {
            group = wheel;
            mode = 0755;
            path = "usr/local/bin/package";
            user = root;
        }
    );
    id = "net.example.package";
    options = "purge_ds_store";
    pkgname = "package-0.7.2.1";
    pkgroot = "/Users/username/Library/AutoPkg/Cache/net.example.package.munki/root";
    version = "0.7.2.1";
}}}
PkgCreator: Connecting
PkgCreator: Sending packaging request
PkgCreator: Disconnecting
{'Output': {'new_package_request': True,
            'pkg_creator_summary_result': {'data': {'identifier': u'net.example.package',
                                                    'pkg_path': '/Users/username/Library/AutoPkg/Cache/net.example.package.munki/package-0.7.2.1.pkg',
                                                    'version': u'0.7.2.1'},
                                           'report_fields': ['identifier',
                                                             'version',
                                                             'pkg_path'],
                                           'summary_text': 'The following packages were built:'},
            'pkg_path': '/Users/username/Library/AutoPkg/Cache/net.example.package.munki/package-0.7.2.1.pkg'}}
net.example.processors.MakeManifests/MakeManifests
{'Input': {'manifests': {
    "manifest_stable" =     (
        "optional_installs"
    );
}}}
{'Output': {}}
net.example.processors.MunkiImporter/MunkiImporter
{'Input': {'MUNKI_REPO': u'/opt/munki',
           'pkg_path': u'/Users/username/Library/AutoPkg/Cache/net.example.package.munki/package-0.7.2.1.pkg',
           'pkginfo': {
    catalogs =     (
        "catalog_stable"
    );
    category = Utilities;
    description = "Package - A tool";
    "display_name" = package;
    "installable_condition" = "tag == \"true\"";
    name = "net.example.package";
}}}
MunkiImporter: Item package-0.7.2.1.pkg already exists in the munki repo as pkgs/package-0.7.2.1.pkg.
{'Output': {'pkg_repo_path': u'/opt/munki/pkgs/package-0.7.2.1.pkg'}}
{'AUTOPKG_VERSION': u'1.4.1',
 'CHECK_FILESIZE_ONLY': False,
 'CURL_PATH': '/usr/bin/curl',
 u'DISPLAY_NAME': u'package',
 u'MUNKI_REPO': u'/opt/munki',
 u'MUNKI_REPO_SUBDIR': u'apps/net.example.package',
 u'NAME': u'net.example.package',
 'PARENT_RECIPES': ['/Users/username/devel/munki-autopkg/net.example.package/net.example.package.download.recipe'],
 'RECIPE_CACHE_DIR': u'/Users/username/Library/AutoPkg/Cache/net.example.package.munki',
 'RECIPE_DIR': '/Users/username/devel/munki-autopkg/net.example.package',
 'RECIPE_OVERRIDE_DIRS': ['~/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': '/Users/username/devel/munki-autopkg/net.example.package/net.example.package.munki.recipe',
 'RECIPE_SEARCH_DIRS': ['.',
                        '~/Library/AutoPkg/Recipes',
                        '/Library/AutoPkg/Recipes',
                        '/Users/username/devel/munki-autopkg/net.example.package'],
 u'cmd': u'#!/bin/bash\nset -e\ntar -C /Users/username/Library/AutoPkg/Cache/net.example.package.munki -Jxpvf /Users/username/Library/AutoPkg/Cache/net.example.package.munki/downloads/net.example.package-0.7.2.tar.xz\n',
 u'destination_path': u'/Users/username/Library/AutoPkg/Cache/net.example.package.munki/root/usr/local/bin/package',
 'download_changed': False,
 'etag': '',
 u'filename': u'net.example.package-0.7.2.tar.xz',
 u'force_pkg_build': u'True',
 u'intversion': '1',
 'last_modified': '',
 u'manifests': {
    "manifest_stable" =     (
        "optional_installs"
    );
},
 'munki_info': {},
 'munki_repo_changed': False,
 'new_package_request': True,
 u'overwrite': u'true',
 'pathname': u'/Users/username/Library/AutoPkg/Cache/net.example.package.munki/downloads/net.example.package-0.7.2.tar.xz',
 'pkg_creator_summary_result': {'data': {'identifier': u'net.example.package',
                                         'pkg_path': '/Users/username/Library/AutoPkg/Cache/net.example.package.munki/package-0.7.2.1.pkg',
                                         'version': u'0.7.2.1'},
                                'report_fields': ['identifier',
                                                  'version',
                                                  'pkg_path'],
                                'summary_text': 'The following packages were built:'},
 'pkg_path': u'/Users/username/Library/AutoPkg/Cache/net.example.package.munki/package-0.7.2.1.pkg',
 'pkg_repo_path': u'/opt/munki/pkgs/package-0.7.2.1.pkg',
 u'pkg_request': {
    chown =     (
                {
            group = wheel;
            mode = 0755;
            path = "usr/local/bin/package";
            user = root;
        }
    );
    id = "net.example.package";
    infofile = "";
    options = "purge_ds_store";
    pkgdir = "/Users/username/Library/AutoPkg/Cache/net.example.package.munki";
    pkgname = "package-0.7.2.1";
    pkgroot = "/Users/username/Library/AutoPkg/Cache/net.example.package.munki/root";
    pkgtype = flat;
    resources = "";
    scripts = "";
    version = "0.7.2.1";
},
 u'pkgdirs': {
    usr = 0755;
    "usr/local" = 0755;
    "usr/local/bin" = 0755;
},
 u'pkginfo': {
    catalogs =     (
        "catalog_stable"
    );
    category = Utilities;
    description = "Package - A tool";
    "display_name" = package;
    "installable_condition" = "tag == \"true\"";
    name = "net.example.package";
},
 'pkginfo_repo_path': '',
 u'pkgroot': u'/Users/username/Library/AutoPkg/Cache/net.example.package.munki/root',
 u'plist_keys': {
    InternalVersion = intversion;
},
 u'plist_path': u'/Users/username/devel/munki-autopkg/net.example.package/_config',
 'prefetch_filename': False,
 u're_pattern': u'package-v([0-9\\.]+).darwin.x86_64.tar.xz',
 'readplist_output_variables': {u'intversion': 1},
 u'result_output_var_name': u'version',
 u'source_path': u'/Users/username/devel/munki-autopkg/net.example.package/_config',
 u'url': u'https://github.com/user/package/releases/download/v0.7.2/package-v0.7.2.darwin.x86_64.tar.xz',
 'verbose': 3,
 u'version': '0.7.2',
 'working_dir': '/Users/username/devel/munki-autopkg'}
Receipt written to /Users/username/Library/AutoPkg/Cache/net.example.package.munki/receipts/net.example.package.munki-receipt-20210512-095447.plist

The following packages were built:
    Identifier            Version  Pkg Path                                                                                 
    ----------            -------  --------                                                                                 
    net.example.package  0.7.2.1  /Users/username/Library/AutoPkg/Cache/net.example.package.munki/package-0.7.2.1.pkg  
```

**Comment by nmcspadden** [comment]
This seems pretty reasonable to me, but please change the target of this PR to the dev branch instead of master.

**Comment by nmcspadden** [comment]
I'm slightly confused as to the `AUTOPKG_VERSION = 1.4.1` statement, as the current version in master is 2.3.2.

**Comment by Ritbit** [comment]
Regardless the of autopkg version: The regex is clearly missing support for a dash (-) as acceptable character in the version number. 
Since the dash is also used in regex to specify a range of characters it has to be the last character in the class specification.

**Comment by gfa** [comment]
> I'm slightly confused as to the `AUTOPKG_VERSION = 1.4.1` statement, as the current version in master is 2.3.2.

Hi

that is correct, this was tested against 1.4.1 instead of master, I really don't have an environment where I can simply install autopkg from git and test it.

Could you point me to a doc/recipe/test case I can look up and set a test environment easily? then i would try to re run this against master

besides, the regex hasn't been touched since `29cbe1c0ca598` (formatting commit) and meaningfully since `e540f3be04ca7` (import from svn) I don't think it matters much the version is used to test.



I really don't have the toolchain to

**Comment by gfa** [comment]
I made a bunch of pushes to base on top of `dev` instead of `master`, also I've changed the target to `dev`

**Pull request merged**
