### PR TITLE
Add links for easy comparison of previous versions.

### PR DESCRIPTION
**Pull request by homebysix**

### CODE REVIEW

**Comment by arubdesu** [comment]
+1

**Comment by gregneagle** [comment]
I'll merge this, but if Tim and I forget to add links in the future, I hope you will...

**Comment by homebysix** [comment]
Deal.

**Comment by timsutton** [comment]
This looks helpful, although it _might_ break a search/regex done in the release script. Would be worth investigating whatever minor change is needed there, too.

**Comment by timsutton** [comment]
Release script updated: https://github.com/autopkg/autopkg/commit/18fb1e2454a198835f98113f7da70a00cefc52ea

**Pull request merged**
