### PR TITLE
Use a temporary file in CURLDownloader

### PR DESCRIPTION
**Pull request by hjuutilainen**
I decided to go with using a temporary file and move it in place if the processor downloaded something new. This imports the tempfile module.

### CODE REVIEW

**Comment by timsutton** [comment]
Without having looked too closely at why, I'm running TheUnarchiver.munki with a clean cache and get a failure when you try the `os.rename()`:

```
➜  autopkg git:(ba966c7) ✗ Code/autopkg run TheUnarchiver.munki -v
Processing TheUnarchiver.munki...
SparkleUpdateInfoProvider
SparkleUpdateInfoProvider: Version retrieved from appcast: 103
SparkleUpdateInfoProvider: User-facing version retrieved from appcast: 3.10.1
SparkleUpdateInfoProvider: Copied key minimum_os_version from Sparkle feed to additional pkginfo.
SparkleUpdateInfoProvider: Found URL https://wakaba.c3.cx/releases/TheUnarchiver/TheUnarchiver3.10.1.zip
CURLDownloader
Can't move /Users/tsutton/Library/AutoPkg/Cache/local.TheUnarchiver.munki/downloads/tmp7uACD5 to /Users/tsutton/Library/AutoPkg/Cache/local.TheUnarchiver.munki/downloads/TheUnarchiver3.10.1.zip
Failed.
Receipt written to /Users/tsutton/Library/AutoPkg/Cache/local.TheUnarchiver.munki/receipts/TheUnarchiver-receipt-20151111-104149.plist

The following recipes failed:
    TheUnarchiver.munki
        Error in local.TheUnarchiver.munki: Processor: CURLDownloader: Error: Can't move /Users/tsutton/Library/AutoPkg/Cache/local.TheUnarchiver.munki/downloads/tmp7uACD5 to /Users/tsutton/Library/AutoPkg/Cache/local.TheUnarchiver.munki/downloads/TheUnarchiver3.10.1.zip

Nothing downloaded, packaged or imported.
```

**Comment by hjuutilainen** [comment]
Hmm, I'm not seeing this. Tested with both empty and existing cache.

**Comment by hjuutilainen** [comment]
Anything special in your cache path that os.rename can't handle?

**Comment by hjuutilainen** [comment]
Changed the renaming to try/except block.

**Comment by hjuutilainen** [comment]
Should there be a check/remove functionality for existing zero byte output file? This would exist if a recipe with current CURLDownloader has been run at least two times but which has not downloaded new items. Otherwise recipes with CURLDownloader and existing cache will fail until new downloads are available:

```
The following recipes failed:
    /Volumes/autopkg/munki-autopkg-20151112090926.2bdO1b/auth-recipes/TheUnarchiver.munki.recipe
        Error in local.munki.TheUnarchiver: Processor: Unarchiver: Error: Unarchiving /Users/autopkg/Library/AutoPkg/Cache/local.munki.TheUnarchiver/downloads/TheUnarchiver3.10.1.zip with ditto failed: ditto: Couldn't read PKZip signature

    /Volumes/autopkg/munki-autopkg-20151112090926.2bdO1b/auth-recipes/Vagrant.munki.recipe
        Error in local.munki.Vagrant: Processor: CodeSignatureVerifier: Error: /Users/autopkg/Library/AutoPkg/Cache/local.munki.Vagrant/downloads/Vagrant.dmg is not mounted
```

**Comment by timsutton** [comment]
I should think so. I'm not sure how much more complicated this makes the code in order to handle pre-existing downloaded items (with their "expected" `pathname` filenames).

**Comment by hjuutilainen** [comment]
Thinking about this more, I think the best way is to just remove the file if it's size is zero bytes. I can't think of any valid reason why a zero byte output file would be a desired outcome of this processor. Simple fix committed.

**Comment by timsutton** [comment]
LGTM. Thank you!

**Pull request merged**
