### PR TITLE
Create unit test for FileCreator

### PR DESCRIPTION
**Pull request by homebysix**

### CODE REVIEW

**Comment by nmcspadden** [comment]
Are you still intending to add to this, or is it ready for review now? Your skeleton is fine, but the unit test itself doesn't do much.

**Comment by homebysix** [comment]
Let me take a shot at the mock_open, and if I can get that sorted I’ll remove the WIP.

**Comment by homebysix** [comment]
OK, I think I got it. Whether it's a useful test is debatable.

```
% python3 -m unittest tests.test_filecreator -v
test_file_content (tests.test_filecreator.TestFileCreator)
The file created by the processor should have the expected contents. ... ok

----------------------------------------------------------------------
Ran 1 test in 0.008s

OK
```

**Comment by nmcspadden** [comment]
This is good! 

In a future PR, I think we should add a few more tests:
* Opening a bad file path should trigger a ProcessorError
* Opening a good file path should _not_ trigger any error
* Test the file mode is created as expected
* Failing to set the file mode, if defined, should trigger a ProcessorError

**Comment by nmcspadden** [comment]
Additionally, we should ensure we have the correct copyright headers on all files in the repo.

**Pull request merged**
