### PR TITLE
Removing temporary file when CHECK_FILESIZE_ONLY is true and download_changed is false

### PR DESCRIPTION
**Pull request by fuzzylogiq**
I think this explains why foigus was seeing this issue https://groups.google.com/forum/#!topic/autopkg-discuss/z7_jMuioOJU/discussion and hopefully fixes it.

### CODE REVIEW

**Comment by fuzzylogiq** [comment]
ok i realise that this is slightly more involved - it shouldn't download the temp file at all...bear with me.

**Comment by fuzzylogiq** [comment]
I'm actually leaning towards a bit of a rewrite of URLDownloader.py here that checks the headers first before getting the content, as there's no equivalent to the "If-None-Match" and "If-Modified-Since" request headers for content-length.

**Comment by jessepeterson** [comment]
Hey @fuzzylogiq, came across this from #318. But: before jumping in on rewriting URLDownloader I'd suggest taking a look some of the rewrites in [reposado](https://github.com/wdas/reposado)'s curl download code. Like this: wdas/reposado@18f8dc2e3651d6e6b28f94eec2b3b81dc5dacb7c and this: wdas/reposado@e071ea753f4ac566033e389839c52e67d87b33d4, etc. I'd like to see URLDownloader also not download a file when `CHECK_FILESIZE_ONLY` is set so I'm happy to contribute to this effort when I can, too.

**Comment by jessepeterson** [comment]
Also just a quick note: I think this should be merged as this one line change at least solves the superfluous disk usage issue. The larger issues at hand (refactoring/improving URLDownloader and implementing support to not download at all) can be tackled separately.

**Comment by fuzzylogiq** [comment]
My question here is really if we:

a) just add the check to see if content-length has changed prior to attempting a download (so a curl header request only) and keep the rest of URLDownloader as is or
b) write new conditionals for the e-tag/modified headers in addition to the content-length one in a) and remove the lines https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/URLDownloader.py#L186-L190 that leverage curl's internal checks.

It would be a good idea to merge in your changes to handle proxy headers too.

**Comment by fuzzylogiq** [comment]
My question here is really if we:

a) just add the check to see if content-length has changed prior to attempting a download (so a curl header request only) and keep the rest of URLDownloader as is or
b) write new conditionals for the e-tag/modified headers in addition to the content-length one in a) and remove the lines https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/URLDownloader.py#L186-L190 that leverage curl's internal checks.

It would be a good idea to merge in your changes to handle proxy headers too.

**Comment by fuzzylogiq** [comment]
My question here is really if we:

a) just add the check to see if content-length has changed prior to attempting a download (so a curl header request only) and keep the rest of URLDownloader as is or
b) write new conditionals for the e-tag/modified headers in addition to the content-length one in a) and remove the lines https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/URLDownloader.py#L186-L190 that leverage curl's internal checks.

It would be a good idea to merge in your changes to handle proxy headers too.

**Comment by fuzzylogiq** [comment]
My question here is really if we:

a) just add the check to see if content-length has changed prior to attempting a download (so a curl header request only) and keep the rest of URLDownloader as is or
b) write new conditionals for the e-tag/modified headers in addition to the content-length one in a) and remove the lines https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/URLDownloader.py#L186-L190 that leverage curl's internal checks.

It would be a good idea to merge in your changes to handle proxy headers too.

**Comment by fuzzylogiq** [comment]
My question here is really if we:

a) just add the check to see if content-length has changed prior to attempting a download (so a curl header request only) and keep the rest of URLDownloader as is or
b) write new conditionals for the e-tag/modified headers in addition to the content-length one in a) and remove the lines https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/URLDownloader.py#L186-L190 that leverage curl's internal checks.

It would be a good idea to merge in your changes to handle proxy headers too.

**Comment by fuzzylogiq** [comment]
My question here is really if we:

a) just add the check to see if content-length has changed prior to attempting a download (so a curl header request only) and keep the rest of URLDownloader as is or
b) write new conditionals for the e-tag/modified headers in addition to the content-length one in a) and remove the lines https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/URLDownloader.py#L186-L190 that leverage curl's internal checks.

It would be a good idea to merge in your changes to handle proxy headers too.

**Comment by fuzzylogiq** [comment]
My question here is really if we:

a) just add the check to see if content-length has changed prior to attempting a download (so a curl header request only) and keep the rest of URLDownloader as is or
b) write new conditionals for the e-tag/modified headers in addition to the content-length one in a) and remove the lines https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/URLDownloader.py#L186-L190 that leverage curl's internal checks.

It would be a good idea to merge in your changes to handle proxy headers too.

**Comment by fuzzylogiq** [comment]
My question here is really if we:

a) just add the check to see if content-length has changed prior to attempting a download (so a curl header request only) and keep the rest of URLDownloader as is or
b) write new conditionals for the e-tag/modified headers in addition to the content-length one in a) and remove the lines https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/URLDownloader.py#L186-L190 that leverage curl's internal checks.

It would be a good idea to merge in your changes to handle proxy headers too.

**Comment by fuzzylogiq** [comment]
My question here is really if we:

a) just add the check to see if content-length has changed prior to attempting a download (so a curl header request only) and keep the rest of URLDownloader as is or
b) write new conditionals for the e-tag/modified headers in addition to the content-length one in a) and remove the lines https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/URLDownloader.py#L186-L190 that leverage curl's internal checks.

It would be a good idea to merge in your changes to handle proxy headers too.

**Comment by fuzzylogiq** [comment]
My question here is really if we:

a) just add the check to see if content-length has changed prior to attempting a download (so a curl header request only) and keep the rest of URLDownloader as is or
b) write new conditionals for the e-tag/modified headers in addition to the content-length one in a) and remove the lines https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/URLDownloader.py#L186-L190 that leverage curl's internal checks.

It would be a good idea to merge in your changes to handle proxy headers too.

**Comment by fuzzylogiq** [comment]
My question here is really if we:

a) just add the check to see if content-length has changed prior to attempting a download (so a curl header request only) and keep the rest of URLDownloader as is or
b) write new conditionals for the e-tag/modified headers in addition to the content-length one in a) and remove the lines https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/URLDownloader.py#L186-L190 that leverage curl's internal checks.

It would be a good idea to merge in your changes to handle proxy headers too.

**Comment by fuzzylogiq** [comment]
My question here is really if we:

a) just add the check to see if content-length has changed prior to attempting a download (so a curl header request only) and keep the rest of URLDownloader as is or
b) write new conditionals for the e-tag/modified headers in addition to the content-length one in a) and remove the lines https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/URLDownloader.py#L186-L190 that leverage curl's internal checks.

It would be a good idea to merge in your changes to handle proxy headers too.

**Comment by jessepeterson** [comment]
Sure. There's also some changes happening in #316. Considering this may span any processor that wants to download stuff, I wonder if a base `CurlDownloaderProcessor` base class (that subsequently inherits  from `Processor`. E.g. kind of in the vain of `DmgMounter`.

**Pull request closed without merging**
