### PR TITLE
Fix Changelog links

### PR DESCRIPTION
**Pull request by clburlison**
Now all links actually work.

### CODE REVIEW

**Comment by homebysix** [comment]
Oh interesting. GitHub sees `[something] (something)` and assumes the space between is a mistake. My markdown preview package doesn't do that. Good catch.

Looks like you lost the space before the date on version 0.4.1, though.

**Comment by timsutton** [comment]
Have you already tested simply:

`[0.5.0](https://github.com/autopkg/autopkg/compare/v0.4.2...v0.5.0)  (July 17, 2015)`

..to avoid having to maintain the list of links at the bottom?

**Comment by clburlison** [comment]
@timsutton PR is updated with that markdown syntax. Hopefully that makes it easier to maintain.

**Comment by timsutton** [comment]
Thanks, I cherry-picked these commits to avoid a merge. Going back to look at the release script turned up something else I needed to update anyway.

**Pull request closed without merging**
