### PR TITLE
Fix isort newlines

### PR DESCRIPTION
**Pull request by MichalMMac**
Mostly removes extra newlines to make `isort` happy.

### CODE REVIEW

**Comment by nmcspadden** [comment]
This now has to be rebased due to the changes in #534 .

**Comment by MichalMMac** [comment]
Done.

**Comment by nmcspadden** [comment]
@gregneagle Seem reasonable?

**Comment by gregneagle** [comment]
GitHub is telling me there are conflicts now, probably because I just merged log() vs print() PR.

**Comment by gregneagle** [comment]
Even if/when the merge conflicts are addressed, I'm not too keen on looking at 49 files with what should be nothing but formatting changes... I'll let Nick do it...

**Comment by MichalMMac** [comment]
Rebased and ready to merge @nmcspadden

**Comment by nmcspadden** [comment]
Approved!

**Pull request merged**
