### PR TITLE
Added FTP response checking to URLDownloader processor

### PR DESCRIPTION
**Pull request by overhacked**
I found that for **ftp://** URLs (like those used by HP in their product driver downloads), autopkg always reports the file as newly downloaded. This patch allows `URLDownloader` to at least grab the file size from the FTP 213 response code that curl elicits by default via a SIZE command.

I also check for FTP success (125 or 150) and failure (55x) and map it to HTTP 200 and 404 in case any future changes check for those values in `header['http_result_code']`.

### CODE REVIEW

**Comment by gregneagle** [comment]
Looks reasonable to me; I've called for some additional eyes on it.

**Comment by gregneagle** [comment]
Please see https://groups.google.com/d/msg/autopkg-discuss/kdrvz2UR2eo/-Y-fbxI1CAAJ

**Comment by timsutton** [comment]
It looks good to me as well. I didn't write any of URLDownloader's header parsing code so I'm much less familiar with it, but is it ok that `donewithheaders = True` is set only for the `150` or `125` response codes?

**Comment by overhacked** [comment]
I think setting `donewithheaders = True` only on success follows the pattern of the pre-existing HTTP response-handling code. Curl exits quickly on failure, and there is also a catch-all `else` that will set `donewithheaders = True` when the while-loop hits a blank line (or end of input). The only difference with FTP is that there won't be any blank lines unless cURL changes its output format. End of input comes after the file transfer is complete and cURL closes stdout, so staying in the while-loop until then is basically the same as the current behavior, synchronously waiting on the process to exit.

**Comment by overhacked** [comment]
I saw no objections on the Google Groups review thread. Could you consider merging this for the next release?

Apologies if there is a PR policy in place that I'm unaware of.

**Comment by timsutton** [comment]
I don't have any objections, and think it's worth merging. There's no formal PR policy, don't worry, you didn't miss anything.

**Pull request merged**
