### PR TITLE
Add repo as submodule when autopkg settings is versioned

### PR DESCRIPTION
**Pull request by ygini**
This change allow the autopkg working folder to be versioned by git.

The goal is to allow IT to manage the whole autopkg setup under git and so, repo should be added as submodule instead of simple clone.

Managing repo as submodule with a versioned autopkg config will allow a team to execute autopkg on multiple workstation and still relying on the same list of repo with the same validated version for each.

For example, if the IT team do its security job and check each repo update before accepting it, submodule can be used to track this validation.

### CODE REVIEW

**Comment by ygini** [comment]
For information, I use this change on my own setup for almost a month without any issue.

**Comment by gregneagle** [comment]
Does this change affect repo-update or repo-delete ?

**Comment by ygini** [comment]
Hi

The update process is handled. Not the delete one, I've missed it. 

Don't merge the PR yet, I will submit ASAP the missing part.

**Comment by ygini** [comment]
Support for delete added, and an issue found and fixed in the same time.

**Pull request closed without merging**
