### PR TITLE
URLGetter refactoring and HTTP proxy fix

### LINKED ISSUE #416: Not working with HTTP proxy since 1.0.4
I use AutoPkg on macOS which always uses HTTP(S) proxy for HTTP(S) connections.
Proxy is configured via environment variables. Since 1.0.4 I get following crash when doing `autopkg searxh xyz` or when running some recipes which connect to Github. This is probably related to change `GitHub API requests are now performed using curl. ` made in 1.0.4.

```
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 2453, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2447, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 912, in search_recipes
    results = do_gh_code_search(query, use_token=options.use_token)
  File "/usr/local/bin/autopkg", line 826, in do_gh_code_search
    accept="application/vnd.github.v3.text-match+json")
  File "/Library/AutoPkg/autopkglib/github/__init__.py", line 209, in call_api
    resp_data = json.loads(page_content)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
``` 

macOS: 10.13.4
Clean install with comand-line tools installed.
Current workaround: Downgrade to 1.0.3

### PR DESCRIPTION
**Pull request by MichalMMac**
My original goal was to fix problem with autopkg not downloading files through HTTP proxy #416 
However when going through the code I found out it was somewhat unsatisfactory (very long functions, bad coding habits , etc.). Only thing to do was the *Right Thing* -> bit of refactoring.

- This PR introduces `URLGetter` class (suggested in https://github.com/autopkg/autopkg/issues/416#issuecomment-386764735). `URLGetter` is responsible for launching `curl` via subprocess and handling generic `curl` functionality like parsing HTTP headers. Classes `URLDownloader`, `URLTextSearcher`, `GitHubSession`, and `SparkleUpdateInfoProvider` are now subclasses of `URLGetter`. 
- HTTP header parsing is now done after the download. There is no infinite loop with break conditions, polling the subprocesses for output and magic constants like `maxheaders`.
- Code in classes  `URLDownloader`, `URLTextSearcher`, `GitHubSession`, and `SparkleUpdateInfoProvider` has been refactored. I tried to split it into sensible methods. Almost all `pylint` issues are now fixed.
- Refactoring the code handling `subprocess` and HTTP header parsing Fixes #416 by itself
- Fixes [issue](https://groups.google.com/forum/#!topic/autopkg-discuss/E6o9iHsSLSs) with redownloading files when using proxy 
- `curl_opts` input variable is now present in all subclasses of `URLGetter`.
- ~~https://github.com/MichalMMac/autopkg/commit/c0024278099cf3841a776c9005a7426ca0df9802  attempts to deal with #432. There is  a new `rename_after_redirect` input variable in `URLDownloader`. See the description.~~

I tried to [reach out](https://groups.google.com/forum/#!topic/autopkg-discuss/i4FswIat6GA) to AutoPkg google group and MacSysAdmin slack channel without much success. Fellow admins with same problem #416 tested my code successfully. However I belive this PR could use more testing (and RC version if merged).

### CODE REVIEW

**Comment by hjuutilainen** [comment]
Thank you for submitting a PR for this. That's a lot of changes but let's start going through it. I'll start running your code with my testing runs and see if I come up with follow-up questions.

**Comment by gregneagle** [comment]
Very very large PRs like this are quite difficult for a loose group of people who don't have a lot of spare time to review and merge with confidence. I appreciate that you wanted to do this "right", but the sheer volume of changes have discouraged me from reviewing it.

In addition, the core maintainers would be "on the hook" for future maintenance and support of the code, so we not only have to agree it works as we all want, but we have to make sure it is something we understand and support.

Of course the existing code can be better, but you don't encourage us much when you write things like "However when going through the code I found out it was somewhat unsatisfactory (very long functions, bad coding habits , etc.)." and "the code wasn't very nice" (in an earlier version of your PR). Those judgements might be _true_ but they don't encourage the current maintainers (who _wrote_ the code you dislike) to look at your replacements.

It's good that Hannes is taking a look, though.

**Comment by MichalMMac** [comment]
I rebased the branch curlrefactor onto the current master.

Rename after redirect feature was moved to separate branch [rename_after_redirect](https://github.com/MichalMMac/autopkg/tree/rename_after_redirect) to simplify this this PR.

If there are any questions or tips how should I improve this I am happy to hear them and I can work on this a bit more.

Testing in my environment (3 monhts, running regularly around 80 recipes) looks good so far. I fixes issues with proxy I had and I am happy with the result :-)

**Comment by MichalMMac** [comment]
Rebased onto current master with Python3 changes. I am going to test this today and update this comment with results.

Note: `log()` and `log_err()` could be used as `print()` wrappers so we don't have to do         `file=sys.stderr` everywhere.

**Comment by MichalMMac** [comment]
I rebased this PR  #446 onto `printlog` branch for #527 which should me merged first.

All the latest black, flake8 and isort changes shoud be incorporated now.

**Comment by MichalMMac** [comment]
Would it better to split this PR into 7 separate pull request?
One for new URLGetter procesor and others for each other procesor file newly using the URLGetter.

**Comment by nmcspadden** [comment]
That would make it significantly easier to review, yes. Ideally, you want to aim for minimal changes in each PR to make review and testing simpler.

**Comment by MichalMMac** [comment]
I created separate PR for each class and added some extra tweaks into new commits:

- `URLGetter`: #544 
- `URLDownloader`: #545
- `URLTextSearcher`: #546
- `SparkleUpdateInfoProvider`: #547
- `GitHubSession`: #548
- `GitHubReleasesInfoProvider`: #549

Only thing not in those PRs is commit 7182befc54bcf1f310f837420053519e45d712bb removing `curl_cmd()` from autopkglib. This can be done only after all other PRs are merged.

Changes to any of these PRs are going to be also copied to branch `curlrefactor` (This PR) so I can test it in my environment.

**Comment by nmcspadden** [comment]
Given the other PRs are being evaluated, is there something still unique in this one that needs to be included? If so, can the summary and title be updated to correctly reflect what this PR does?

If not, let's close it.

**Comment by MichalMMac** [comment]
Ok. Closing.

**Pull request closed without merging**
